# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2f8c9628f117f6bc08937cc7663c93c1cdb9b5b80d43ba6cbf533e4ee5cf6ca6f0a45a2441a434261bde95f7d7a8bee44a97b164aef780006d6b74de445435ab

test:
  secret_key_base: a665dde37b7b7c20dc5d029d8dfb1d2d7c12f53d7240a9b4e0f2bb74dc55386d3ee881098b70da2fde7ddb62b8107af5e3645322a528ac161ba4863ad27552b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
